package netsdk

/*
#cgo CFLAGS: -I .
#cgo LDFLAGS: -L . -ldhnetsdk

#include <stdio.h>
#include <stdlib.h>
#include "dhnetsdk.h"
*/
import "C"

import "errors"

var (
	ErrLoginFailed    = errors.New("login failed")
	ErrInvalidAddress = errors.New("invalid address format, must have ip and port")
)

func Err(code int) error {
	switch code {
	case C.NET_NOERROR:
		return nil
	case C.NET_ERROR:
		return errors.New("未知错误")
	case C.NET_SYSTEM_ERROR:
		return errors.New("系统出错")
	case C.NET_NETWORK_ERROR:
		return errors.New("网络错误,可能是因为网络超时")
	case C.NET_DEV_VER_NOMATCH:
		return errors.New("设备协议不匹配")
	case C.NET_INVALID_HANDLE:
		return errors.New("句柄无效")
	case C.NET_OPEN_CHANNEL_ERROR:
		return errors.New("打开通道失败")
	case C.NET_CLOSE_CHANNEL_ERROR:
		return errors.New("关闭通道失败")
	case C.NET_ILLEGAL_PARAM:
		return errors.New("用户参数不合法")
	case C.NET_SDK_INIT_ERROR:
		return errors.New("SDK初始化出错")
	case C.NET_SDK_UNINIT_ERROR:
		return errors.New("SDK清理出错")
	case C.NET_RENDER_OPEN_ERROR:
		return errors.New("申请render资源出错")
	case C.NET_DEC_OPEN_ERROR:
		return errors.New("打开解码库出错")
	case C.NET_DEC_CLOSE_ERROR:
		return errors.New("关闭解码库出错")
	case C.NET_MULTIPLAY_NOCHANNEL:
		return errors.New("多画面预览中检测到通道数为0")
	case C.NET_TALK_INIT_ERROR:
		return errors.New("录音库初始化失败")
	case C.NET_TALK_NOT_INIT:
		return errors.New("录音库未经初始化")
	case C.NET_TALK_SENDDATA_ERROR:
		return errors.New("发送音频数据出错")
	case C.NET_REAL_ALREADY_SAVING:
		return errors.New("实时数据已经处于保存状态")
	case C.NET_NOT_SAVING:
		return errors.New("未保存实时数据")
	case C.NET_OPEN_FILE_ERROR:
		return errors.New("打开文件出错")
	case C.NET_PTZ_SET_TIMER_ERROR:
		return errors.New("启动云台控制定时器失败")
	case C.NET_RETURN_DATA_ERROR:
		return errors.New("对返回数据的校验出错")
	case C.NET_INSUFFICIENT_BUFFER:
		return errors.New("没有足够的缓存")
	case C.NET_NOT_SUPPORTED:
		return errors.New("当前SDK未支持该功能")
	case C.NET_NO_RECORD_FOUND:
		return errors.New("查询不到录象")
	case C.NET_NOT_AUTHORIZED:
		return errors.New("无操作权限")
	case C.NET_NOT_NOW:
		return errors.New("暂时无法执行")
	case C.NET_NO_TALK_CHANNEL:
		return errors.New("未发现对讲通道")
	case C.NET_NO_AUDIO:
		return errors.New("未发现音频")
	case C.NET_NO_INIT:
		return errors.New("网络SDK未经初始化")
	case C.NET_DOWNLOAD_END:
		return errors.New("下载已结束")
	case C.NET_EMPTY_LIST:
		return errors.New("查询结果为空")
	case C.NET_ERROR_GETCFG_SYSATTR:
		return errors.New("获取系统属性配置失败")
	case C.NET_ERROR_GETCFG_SERIAL:
		return errors.New("获取序列号失败")
	case C.NET_ERROR_GETCFG_GENERAL:
		return errors.New("获取常规属性失败")
	case C.NET_ERROR_GETCFG_DSPCAP:
		return errors.New("获取DSP能力描述失败")
	case C.NET_ERROR_GETCFG_NETCFG:
		return errors.New("获取网络配置失败")
	case C.NET_ERROR_GETCFG_CHANNAME:
		return errors.New("获取通道名称失败")
	case C.NET_ERROR_GETCFG_VIDEO:
		return errors.New("获取视频属性失败")
	case C.NET_ERROR_GETCFG_RECORD:
		return errors.New("获取录象配置失败")
	case C.NET_ERROR_GETCFG_PRONAME:
		return errors.New("获取解码器协议名称失败")
	case C.NET_ERROR_GETCFG_FUNCNAME:
		return errors.New("获取232串口功能名称失败")
	case C.NET_ERROR_GETCFG_485DECODER:
		return errors.New("获取解码器属性失败")
	case C.NET_ERROR_GETCFG_232COM:
		return errors.New("获取232串口配置失败")
	case C.NET_ERROR_GETCFG_ALARMIN:
		return errors.New("获取外部报警输入配置失败")
	case C.NET_ERROR_GETCFG_ALARMDET:
		return errors.New("获取动态检测报警失败")
	case C.NET_ERROR_GETCFG_SYSTIME:
		return errors.New("获取设备时间失败")
	case C.NET_ERROR_GETCFG_PREVIEW:
		return errors.New("获取预览参数失败")
	case C.NET_ERROR_GETCFG_AUTOMT:
		return errors.New("获取自动维护配置失败")
	case C.NET_ERROR_GETCFG_VIDEOMTRX:
		return errors.New("获取视频矩阵配置失败")
	case C.NET_ERROR_GETCFG_COVER:
		return errors.New("获取区域遮挡配置失败")
	case C.NET_ERROR_GETCFG_WATERMAKE:
		return errors.New("获取图象水印配置失败")
	case C.NET_ERROR_GETCFG_MULTICAST:
		return errors.New("获取配置失败位置：组播端口按通道配置")
	case C.NET_ERROR_SETCFG_GENERAL:
		return errors.New("修改常规属性失败")
	case C.NET_ERROR_SETCFG_NETCFG:
		return errors.New("修改网络配置失败")
	case C.NET_ERROR_SETCFG_CHANNAME:
		return errors.New("修改通道名称失败")
	case C.NET_ERROR_SETCFG_VIDEO:
		return errors.New("修改视频属性失败")
	case C.NET_ERROR_SETCFG_RECORD:
		return errors.New("修改录象配置失败")
	case C.NET_ERROR_SETCFG_485DECODER:
		return errors.New("修改解码器属性失败")
	case C.NET_ERROR_SETCFG_232COM:
		return errors.New("修改232串口配置失败")
	case C.NET_ERROR_SETCFG_ALARMIN:
		return errors.New("修改外部输入报警配置失败")
	case C.NET_ERROR_SETCFG_ALARMDET:
		return errors.New("修改动态检测报警配置失败")
	case C.NET_ERROR_SETCFG_SYSTIME:
		return errors.New("修改设备时间失败")
	case C.NET_ERROR_SETCFG_PREVIEW:
		return errors.New("修改预览参数失败")
	case C.NET_ERROR_SETCFG_AUTOMT:
		return errors.New("修改自动维护配置失败")
	case C.NET_ERROR_SETCFG_VIDEOMTRX:
		return errors.New("修改视频矩阵配置失败")
	case C.NET_ERROR_SETCFG_COVER:
		return errors.New("修改区域遮挡配置失败")
	case C.NET_ERROR_SETCFG_WATERMAKE:
		return errors.New("修改图象水印配置失败")
	case C.NET_ERROR_SETCFG_WLAN:
		return errors.New("修改无线网络信息失败")
	case C.NET_ERROR_SETCFG_WLANDEV:
		return errors.New("选择无线网络设备失败")
	case C.NET_ERROR_SETCFG_REGISTER:
		return errors.New("修改主动注册参数配置失败")
	case C.NET_ERROR_SETCFG_CAMERA:
		return errors.New("修改摄像头属性配置失败")
	case C.NET_ERROR_SETCFG_INFRARED:
		return errors.New("修改红外报警配置失败")
	case C.NET_ERROR_SETCFG_SOUNDALARM:
		return errors.New("修改音频报警配置失败")
	case C.NET_ERROR_SETCFG_STORAGE:
		return errors.New("修改存储位置配置失败")
	case C.NET_AUDIOENCODE_NOTINIT:
		return errors.New("音频编码接口没有成功初始化")
	case C.NET_DATA_TOOLONGH:
		return errors.New("数据过长")
	case C.NET_UNSUPPORTED:
		return errors.New("设备不支持该操作")
	case C.NET_DEVICE_BUSY:
		return errors.New("设备资源不足")
	case C.NET_SERVER_STARTED:
		return errors.New("服务器已经启动")
	case C.NET_SERVER_STOPPED:
		return errors.New("服务器尚未成功启动")
	case C.NET_LISTER_INCORRECT_SERIAL:
		return errors.New("输入序列号有误")
	case C.NET_QUERY_DISKINFO_FAILED:
		return errors.New("获取硬盘信息失败")
	case C.NET_ERROR_GETCFG_SESSION:
		return errors.New("获取连接Session信息")
	case C.NET_USER_FLASEPWD_TRYTIME:
		return errors.New("输入密码错误超过限制次数")
	case C.NET_LOGIN_ERROR_PASSWORD:
		return errors.New("密码不正确")
	case C.NET_LOGIN_ERROR_USER:
		return errors.New("帐户不存在")
	case C.NET_LOGIN_ERROR_TIMEOUT:
		return errors.New("等待登录返回超时")
	case C.NET_LOGIN_ERROR_RELOGGIN:
		return errors.New("帐号已登录")
	case C.NET_LOGIN_ERROR_LOCKED:
		return errors.New("帐号已被锁定")
	case C.NET_LOGIN_ERROR_BLACKLIST:
		return errors.New("帐号已被列为黑名单")
	case C.NET_LOGIN_ERROR_BUSY:
		return errors.New("资源不足,系统忙")
	case C.NET_LOGIN_ERROR_CONNECT:
		return errors.New("登录设备超时,请检查网络并重试")
	case C.NET_LOGIN_ERROR_NETWORK:
		return errors.New("网络连接失败")
	case C.NET_LOGIN_ERROR_SUBCONNECT:
		return errors.New("登录设备成功,但无法创建视频通道,请检查网络状况")
	case C.NET_LOGIN_ERROR_MAXCONNECT:
		return errors.New("超过最大连接数")
	case C.NET_LOGIN_ERROR_PROTOCOL3_ONLY:
		return errors.New("只支持3代协议")
	case C.NET_LOGIN_ERROR_UKEY_LOST:
		return errors.New("未插入U盾或U盾信息错误")
	case C.NET_LOGIN_ERROR_NO_AUTHORIZED:
		return errors.New("客户端IP地址没有登录权限")
	case C.NET_LOGIN_ERROR_USER_OR_PASSOWRD:
		return errors.New("账号或密码错误")
	case C.NET_LOGIN_ERROR_DEVICE_NOT_INIT:
		return errors.New("设备尚未初始化，不能登录，请先初始化设备")
	case C.NET_LOGIN_ERROR_LIMITED:
		return errors.New("登录受限,可能是IP受限、时间段受限、有效期受限")
	case C.NET_RENDER_SOUND_ON_ERROR:
		return errors.New("Render库打开音频出错")
	case C.NET_RENDER_SOUND_OFF_ERROR:
		return errors.New("Render库关闭音频出错")
	case C.NET_RENDER_SET_VOLUME_ERROR:
		return errors.New("Render库控制音量出错")
	case C.NET_RENDER_ADJUST_ERROR:
		return errors.New("Render库设置画面参数出错")
	case C.NET_RENDER_PAUSE_ERROR:
		return errors.New("Render库暂停播放出错")
	case C.NET_RENDER_SNAP_ERROR:
		return errors.New("Render库抓图出错")
	case C.NET_RENDER_STEP_ERROR:
		return errors.New("Render库步进出错")
	case C.NET_RENDER_FRAMERATE_ERROR:
		return errors.New("Render库设置帧率出错")
	case C.NET_RENDER_DISPLAYREGION_ERROR:
		return errors.New("Render库设置显示区域出错")
	case C.NET_RENDER_GETOSDTIME_ERROR:
		return errors.New("Render库获取当前播放时间出错")
	case C.NET_GROUP_EXIST:
		return errors.New("组名已存在")
	case C.NET_GROUP_NOEXIST:
		return errors.New("组名不存在")
	case C.NET_GROUP_RIGHTOVER:
		return errors.New("组的权限超出权限列表范围")
	case C.NET_GROUP_HAVEUSER:
		return errors.New("组下有用户,不能删除")
	case C.NET_GROUP_RIGHTUSE:
		return errors.New("组的某个权限被用户使用,不能出除")
	case C.NET_GROUP_SAMENAME:
		return errors.New("新组名同已有组名重复")
	case C.NET_USER_EXIST:
		return errors.New("用户已存在")
	case C.NET_USER_NOEXIST:
		return errors.New("用户不存在")
	case C.NET_USER_RIGHTOVER:
		return errors.New("用户权限超出组权限")
	case C.NET_USER_PWD:
		return errors.New("保留帐号,不容许修改密码")
	case C.NET_USER_FLASEPWD:
		return errors.New("密码不正确")
	case C.NET_USER_NOMATCHING:
		return errors.New("密码不匹配")
	case C.NET_USER_INUSE:
		return errors.New("账号正在使用中")
	case C.NET_ERROR_GETCFG_ETHERNET:
		return errors.New("获取网卡配置失败")
	case C.NET_ERROR_GETCFG_WLAN:
		return errors.New("获取无线网络信息失败")
	case C.NET_ERROR_GETCFG_WLANDEV:
		return errors.New("获取无线网络设备失败")
	case C.NET_ERROR_GETCFG_REGISTER:
		return errors.New("获取主动注册参数失败")
	case C.NET_ERROR_GETCFG_CAMERA:
		return errors.New("获取摄像头属性失败")
	case C.NET_ERROR_GETCFG_INFRARED:
		return errors.New("获取红外报警配置失败")
	case C.NET_ERROR_GETCFG_SOUNDALARM:
		return errors.New("获取音频报警配置失败")
	case C.NET_ERROR_GETCFG_STORAGE:
		return errors.New("获取存储位置配置失败")
	case C.NET_ERROR_GETCFG_MAIL:
		return errors.New("获取邮件配置失败")
	case C.NET_CONFIG_DEVBUSY:
		return errors.New("暂时无法设置")
	case C.NET_CONFIG_DATAILLEGAL:
		return errors.New("配置数据不合法")
	case C.NET_ERROR_GETCFG_DST:
		return errors.New("获取夏令时配置失败")
	case C.NET_ERROR_SETCFG_DST:
		return errors.New("设置夏令时配置失败")
	case C.NET_ERROR_GETCFG_VIDEO_OSD:
		return errors.New("获取视频OSD叠加配置失败")
	case C.NET_ERROR_SETCFG_VIDEO_OSD:
		return errors.New("设置视频OSD叠加配置失败")
	case C.NET_ERROR_GETCFG_GPRSCDMA:
		return errors.New(`获取CDMA\GPRS网络配置失败`)
	case C.NET_ERROR_SETCFG_GPRSCDMA:
		return errors.New(`设置CDMA\GPRS网络配置失败`)
	case C.NET_ERROR_GETCFG_IPFILTER:
		return errors.New("获取IP过滤配置失败")
	case C.NET_ERROR_SETCFG_IPFILTER:
		return errors.New("设置IP过滤配置失败")
	case C.NET_ERROR_GETCFG_TALKENCODE:
		return errors.New("获取语音对讲编码配置失败")
	case C.NET_ERROR_SETCFG_TALKENCODE:
		return errors.New("设置语音对讲编码配置失败")
	case C.NET_ERROR_GETCFG_RECORDLEN:
		return errors.New("获取录像打包长度配置失败")
	case C.NET_ERROR_SETCFG_RECORDLEN:
		return errors.New("设置录像打包长度配置失败")
	case C.NET_DONT_SUPPORT_SUBAREA:
		return errors.New("不支持网络硬盘分区")
	case C.NET_ERROR_GET_AUTOREGSERVER:
		return errors.New("获取设备上主动注册服务器信息失败")
	case C.NET_ERROR_CONTROL_AUTOREGISTER:
		return errors.New("主动注册重定向注册错误")
	case C.NET_ERROR_DISCONNECT_AUTOREGISTER:
		return errors.New("断开主动注册服务器错误")
	case C.NET_ERROR_GETCFG_MMS:
		return errors.New("获取mms配置失败")
	case C.NET_ERROR_SETCFG_MMS:
		return errors.New("设置mms配置失败")
	case C.NET_ERROR_GETCFG_SMSACTIVATION:
		return errors.New("获取短信激活无线连接配置失败")
	case C.NET_ERROR_SETCFG_SMSACTIVATION:
		return errors.New("设置短信激活无线连接配置失败")
	case C.NET_ERROR_GETCFG_DIALINACTIVATION:
		return errors.New("获取拨号激活无线连接配置失败")
	case C.NET_ERROR_SETCFG_DIALINACTIVATION:
		return errors.New("设置拨号激活无线连接配置失败")
	case C.NET_ERROR_GETCFG_VIDEOOUT:
		return errors.New("查询视频输出参数配置失败")
	case C.NET_ERROR_SETCFG_VIDEOOUT:
		return errors.New("设置视频输出参数配置失败")
	case C.NET_ERROR_GETCFG_OSDENABLE:
		return errors.New("获取osd叠加使能配置失败")
	case C.NET_ERROR_SETCFG_OSDENABLE:
		return errors.New("设置osd叠加使能配置失败")
	case C.NET_ERROR_SETCFG_ENCODERINFO:
		return errors.New("设置数字通道前端编码接入配置失败")
	case C.NET_ERROR_GETCFG_TVADJUST:
		return errors.New("获取TV调节配置失败")
	case C.NET_ERROR_SETCFG_TVADJUST:
		return errors.New("设置TV调节配置失败")
	case C.NET_ERROR_CONNECT_FAILED:
		return errors.New("请求建立连接失败")
	case C.NET_ERROR_SETCFG_BURNFILE:
		return errors.New("请求刻录文件上传失败")
	case C.NET_ERROR_SNIFFER_GETCFG:
		return errors.New("获取抓包配置信息失败")
	case C.NET_ERROR_SNIFFER_SETCFG:
		return errors.New("设置抓包配置信息失败")
	case C.NET_ERROR_DOWNLOADRATE_GETCFG:
		return errors.New("查询下载限制信息失败")
	case C.NET_ERROR_DOWNLOADRATE_SETCFG:
		return errors.New("设置下载限制信息失败")
	case C.NET_ERROR_SEARCH_TRANSCOM:
		return errors.New("查询串口参数失败")
	case C.NET_ERROR_GETCFG_POINT:
		return errors.New("获取预制点信息错误")
	case C.NET_ERROR_SETCFG_POINT:
		return errors.New("设置预制点信息错误")
	case C.NET_SDK_LOGOUT_ERROR:
		return errors.New("SDK没有正常登出设备")
	case C.NET_ERROR_GET_VEHICLE_CFG:
		return errors.New("获取车载配置失败")
	case C.NET_ERROR_SET_VEHICLE_CFG:
		return errors.New("设置车载配置失败")
	case C.NET_ERROR_GET_ATM_OVERLAY_CFG:
		return errors.New("获取atm叠加配置失败")
	case C.NET_ERROR_SET_ATM_OVERLAY_CFG:
		return errors.New("设置atm叠加配置失败")
	case C.NET_ERROR_GET_ATM_OVERLAY_ABILITY:
		return errors.New("获取atm叠加能力失败")
	case C.NET_ERROR_GET_DECODER_TOUR_CFG:
		return errors.New("获取解码器解码轮巡配置失败")
	case C.NET_ERROR_SET_DECODER_TOUR_CFG:
		return errors.New("设置解码器解码轮巡配置失败")
	case C.NET_ERROR_CTRL_DECODER_TOUR:
		return errors.New("控制解码器解码轮巡失败")
	case C.NET_GROUP_OVERSUPPORTNUM:
		return errors.New("超出设备支持最大用户组数目")
	case C.NET_USER_OVERSUPPORTNUM:
		return errors.New("超出设备支持最大用户数目")
	case C.NET_ERROR_GET_SIP_CFG:
		return errors.New("获取SIP配置失败")
	case C.NET_ERROR_SET_SIP_CFG:
		return errors.New("设置SIP配置失败")
	case C.NET_ERROR_GET_SIP_ABILITY:
		return errors.New("获取SIP能力失败")
	case C.NET_ERROR_GET_WIFI_AP_CFG:
		return errors.New("获取WIFI ap配置失败")
	case C.NET_ERROR_SET_WIFI_AP_CFG:
		return errors.New("设置WIFI ap配置失败")
	case C.NET_ERROR_GET_DECODE_POLICY:
		return errors.New("获取解码策略配置失败")
	case C.NET_ERROR_SET_DECODE_POLICY:
		return errors.New("设置解码策略配置失败")
	case C.NET_ERROR_TALK_REJECT:
		return errors.New("拒绝对讲")
	case C.NET_ERROR_TALK_OPENED:
		return errors.New("对讲被其他客户端打开")
	case C.NET_ERROR_TALK_RESOURCE_CONFLICIT:
		return errors.New("资源冲突")
	case C.NET_ERROR_TALK_UNSUPPORTED_ENCODE:
		return errors.New("不支持的语音编码格式")
	case C.NET_ERROR_TALK_RIGHTLESS:
		return errors.New("无权限")
	case C.NET_ERROR_TALK_FAILED:
		return errors.New("请求对讲失败")
	case C.NET_ERROR_GET_MACHINE_CFG:
		return errors.New("获取机器相关配置失败")
	case C.NET_ERROR_SET_MACHINE_CFG:
		return errors.New("设置机器相关配置失败")
	case C.NET_ERROR_GET_DATA_FAILED:
		return errors.New("设备无法获取当前请求数据")
	case C.NET_ERROR_MAC_VALIDATE_FAILED:
		return errors.New("MAC地址验证失败 ")
	case C.NET_ERROR_GET_INSTANCE:
		return errors.New("获取服务器实例失败")
	case C.NET_ERROR_JSON_REQUEST:
		return errors.New("生成的json字符串错误")
	case C.NET_ERROR_JSON_RESPONSE:
		return errors.New("响应的json字符串错误")
	case C.NET_ERROR_VERSION_HIGHER:
		return errors.New("协议版本低于当前使用的版本")
	case C.NET_SPARE_NO_CAPACITY:
		return errors.New("热备操作失败, 容量不足")
	case C.NET_ERROR_SOURCE_IN_USE:
		return errors.New("显示源被其他输出占用")
	case C.NET_ERROR_REAVE:
		return errors.New("高级用户抢占低级用户资源")
	case C.NET_ERROR_NETFORBID:
		return errors.New("禁止入网 ")
	case C.NET_ERROR_GETCFG_MACFILTER:
		return errors.New("获取MAC过滤配置失败")
	case C.NET_ERROR_SETCFG_MACFILTER:
		return errors.New("设置MAC过滤配置失败")
	case C.NET_ERROR_GETCFG_IPMACFILTER:
		return errors.New("获取IP/MAC过滤配置失败")
	case C.NET_ERROR_SETCFG_IPMACFILTER:
		return errors.New("设置IP/MAC过滤配置失败")
	case C.NET_ERROR_OPERATION_OVERTIME:
		return errors.New("当前操作超时 ")
	case C.NET_ERROR_SENIOR_VALIDATE_FAILED:
		return errors.New("高级校验失败 ")
	case C.NET_ERROR_DEVICE_ID_NOT_EXIST:
		return errors.New("设备ID不存在")
	case C.NET_ERROR_UNSUPPORTED:
		return errors.New("不支持当前操作")
	case C.NET_ERROR_PROXY_DLLLOAD:
		return errors.New("代理库加载失败")
	case C.NET_ERROR_PROXY_ILLEGAL_PARAM:
		return errors.New("代理用户参数不合法")
	case C.NET_ERROR_PROXY_INVALID_HANDLE:
		return errors.New("代理句柄无效")
	case C.NET_ERROR_PROXY_LOGIN_DEVICE_ERROR:
		return errors.New("代理登入前端设备失败")
	case C.NET_ERROR_PROXY_START_SERVER_ERROR:
		return errors.New("启动代理服务失败")
	case C.NET_ERROR_SPEAK_FAILED:
		return errors.New("请求喊话失败")
	case C.NET_ERROR_NOT_SUPPORT_F6:
		return errors.New("设备不支持此F6接口调用")
	case C.NET_ERROR_CD_UNREADY:
		return errors.New("光盘未就绪")
	case C.NET_ERROR_DIR_NOT_EXIST:
		return errors.New("目录不存在")
	case C.NET_ERROR_UNSUPPORTED_SPLIT_MODE:
		return errors.New("设备不支持的分割模式")
	case C.NET_ERROR_OPEN_WND_PARAM:
		return errors.New("开窗参数不合法")
	case C.NET_ERROR_LIMITED_WND_COUNT:
		return errors.New("开窗数量超过限制")
	case C.NET_ERROR_UNMATCHED_REQUEST:
		return errors.New("请求命令与当前模式不匹配")
	case C.NET_RENDER_ENABLELARGEPICADJUSTMENT_ERROR:
		return errors.New("Render库启用高清图像内部调整策略出错")
	case C.NET_ERROR_UPGRADE_FAILED:
		return errors.New("设备升级失败")
	case C.NET_ERROR_NO_TARGET_DEVICE:
		return errors.New("找不到目标设备")
	case C.NET_ERROR_NO_VERIFY_DEVICE:
		return errors.New("找不到验证设备")
	case C.NET_ERROR_CASCADE_RIGHTLESS:
		return errors.New("无级联权限")
	case C.NET_ERROR_LOW_PRIORITY:
		return errors.New("低优先级")
	case C.NET_ERROR_REMOTE_REQUEST_TIMEOUT:
		return errors.New("远程设备请求超时")
	case C.NET_ERROR_LIMITED_INPUT_SOURCE:
		return errors.New("输入源超出最大路数限制")
	case C.NET_ERROR_SET_LOG_PRINT_INFO:
		return errors.New("设置日志打印失败")
	case C.NET_ERROR_PARAM_DWSIZE_ERROR:
		return errors.New("入参的dwsize字段出错")
	case C.NET_ERROR_LIMITED_MONITORWALL_COUNT:
		return errors.New("电视墙数量超过上限")
	case C.NET_ERROR_PART_PROCESS_FAILED:
		return errors.New("部分过程执行失败")
	case C.NET_ERROR_TARGET_NOT_SUPPORT:
		return errors.New("该功能不支持转发")
	case C.NET_ERROR_VISITE_FILE:
		return errors.New("访问文件失败")
	case C.NET_ERROR_DEVICE_STATUS_BUSY:
		return errors.New("设备忙")
	case C.NET_USER_PWD_NOT_AUTHORIZED:
		return errors.New("修改密码无权限")
	case C.NET_USER_PWD_NOT_STRONG:
		return errors.New("密码强度不够")
	case C.NET_ERROR_NO_SUCH_CONFIG:
		return errors.New("没有对应的配置")
	case C.NET_ERROR_AUDIO_RECORD_FAILED:
		return errors.New("录音失败")
	case C.NET_ERROR_SEND_DATA_FAILED:
		return errors.New("数据发送失败")
	case C.NET_ERROR_OBSOLESCENT_INTERFACE:
		return errors.New("废弃接口")
	case C.NET_ERROR_INSUFFICIENT_INTERAL_BUF:
		return errors.New("内部缓冲不足")
	case C.NET_ERROR_NEED_ENCRYPTION_PASSWORD:
		return errors.New("修改设备ip时,需要校验密码")
	case C.NET_ERROR_NOSUPPORT_RECORD:
		return errors.New("设备不支持此记录集")
	case C.NET_ERROR_SERIALIZE_ERROR:
		return errors.New("数据序列化错误")
	case C.NET_ERROR_DESERIALIZE_ERROR:
		return errors.New("数据反序列化错误")
	case C.NET_ERROR_LOWRATEWPAN_ID_EXISTED:
		return errors.New("该无线ID已存在")
	case C.NET_ERROR_LOWRATEWPAN_ID_LIMIT:
		return errors.New("无线ID数量已超限")
	case C.NET_ERROR_LOWRATEWPAN_ID_ABNORMAL:
		return errors.New("无线异常添加")
	case C.NET_ERROR_ENCRYPT:
		return errors.New("加密数据失败")
	case C.NET_ERROR_PWD_ILLEGAL:
		return errors.New("新密码不合规范")
	case C.NET_ERROR_DEVICE_ALREADY_INIT:
		return errors.New("设备已经初始化")
	case C.NET_ERROR_SECURITY_CODE:
		return errors.New("安全码错误")
	case C.NET_ERROR_SECURITY_CODE_TIMEOUT:
		return errors.New("安全码超出有效期")
	case C.NET_ERROR_GET_PWD_SPECI:
		return errors.New("获取密码规范失败")
	case C.NET_ERROR_NO_AUTHORITY_OF_OPERATION:
		return errors.New("无权限进行该操作")
	case C.NET_ERROR_DECRYPT:
		return errors.New("解密数据失败")
	case C.NET_ERROR_2D_CODE:
		return errors.New("2D code校验失败")
	case C.NET_ERROR_INVALID_REQUEST:
		return errors.New("非法的RPC请求")
	case C.NET_ERROR_PWD_RESET_DISABLE:
		return errors.New("密码重置功能已关闭")
	case C.NET_ERROR_PLAY_PRIVATE_DATA:
		return errors.New("显示私有数据，比如规则框等失败")
	case C.NET_ERROR_ROBOT_OPERATE_FAILED:
		return errors.New("机器人操作失败")
	case C.NET_ERROR_PHOTOSIZE_EXCEEDSLIMIT:
		return errors.New("图片大小超限")
	case C.NET_ERROR_USERID_INVALID:
		return errors.New("用户ID不存在")
	case C.NET_ERROR_EXTRACTFEATURE_FAILED:
		return errors.New("照片特征值提取失败")
	case C.NET_ERROR_PHOTO_EXIST:
		return errors.New("照片已存在")
	case C.NET_ERROR_PHOTO_OVERFLOW:
		return errors.New("照片数量超过上限")
	case C.NET_ERROR_CHANNEL_ALREADY_OPENED:
		return errors.New("通道已经打开")
	case C.NET_ERROR_CREATE_SOCKET:
		return errors.New("创建套接字失败")
	case C.NET_ERROR_CHANNEL_NUM:
		return errors.New("通道号错误")
	case C.NET_ERROR_PHOTO_FORMAT:
		return errors.New("图片格式错误")
	case C.NET_ERROR_DIGITAL_CERTIFICATE_INTERNAL_ERROR:
		return errors.New("内部错误(比如：相关硬件问题，获取公钥失败，内部接口调用失败，写文件失败等等)")
	case C.NET_ERROR_DIGITAL_CERTIFICATE_GET_ID_FAILED:
		return errors.New("获取设备ID失败")
	case C.NET_ERROR_DIGITAL_CERTIFICATE_IMPORT_ILLEGAL:
		return errors.New("证书文件非法(格式不支持或者不是证书文件)")
	case C.NET_ERROR_DIGITAL_CERTIFICATE_SN_ERROR:
		return errors.New("证书sn重复或错误或不规范")
	case C.NET_ERROR_DIGITAL_CERTIFICATE_COMMON_NAME_ILLEGAL:
		return errors.New("证书commonName非法(本地设备证书与系统中的不匹配devid_cryptoID,或者对端的不符合规则(devid_crytoID))")
	case C.NET_ERROR_DIGITAL_CERTIFICATE_NO_ROOT_CERT:
		return errors.New("根证书未导入或不存在")
	case C.NET_ERROR_DIGITAL_CERTIFICATE_CERT_REVOKED:
		return errors.New("证书被吊销")
	case C.NET_ERROR_DIGITAL_CERTIFICATE_CERT_INVALID:
		return errors.New("证书不可用或未生效或已过期")
	case C.NET_ERROR_DIGITAL_CERTIFICATE_CERT_ERROR_SIGN:
		return errors.New("证书签名不匹配")
	case C.NET_ERROR_DIGITAL_CERTIFICATE_COUNTS_UPPER_LIMIT:
		return errors.New("超出证书导入上限")
	case C.NET_ERROR_DIGITAL_CERTIFICATE_CERT_NO_EXIST:
		return errors.New("证书文件不存在(导出证书或者获取对应证书的公钥)")
	case C.NET_ERROR_DEFULAT_SEARCH_PORT:
		return errors.New("默认搜索端口无法使用（5050,37810）")
	case C.NET_ERROR_FACE_RECOGNITION_SERVER_MULTI_APPEND_STOUP:
		return errors.New("批量添加人脸停止")
	case C.NET_ERROR_FACE_RECOGNITION_SERVER_MULTI_APPEND_ERROR:
		return errors.New("批量添加人脸失败")
	case C.NET_ERROR_FACE_RECOGNITION_SERVER_GROUP_ID_EXCEED:
		return errors.New("组ID超过最大值")
	case C.NET_ERROR_FACE_RECOGNITION_SERVER_GROUP_ID_NOT_IN_REGISTER_GROUP:
		return errors.New("组ID不存在或为空")
	case C.NET_ERROR_FACE_RECOGNITION_SERVER_PICTURE_NOT_FOUND:
		return errors.New("无图片数据")
	case C.NET_ERROR_FACE_RECOGNITION_SERVER_GENERATE_GROUP_ID_FAILED:
		return errors.New("生成组ID超出范围")
	case C.NET_ERROR_FACE_RECOGNITION_SERVER_SET_CONFIG_FAILED:
		return errors.New("设置配置失败")
	case C.NET_ERROR_FACE_RECOGNITION_SERVER_FILE_OPEN_FAILED:
		return errors.New("图片文件打开失败")
	case C.NET_ERROR_FACE_RECOGNITION_SERVER_FILE_READ_FAILED:
		return errors.New("图片文件读取失败")
	case C.NET_ERROR_FACE_RECOGNITION_SERVER_FILE_WRITE_FAILED:
		return errors.New("图片文件写入失败")
	case C.NET_ERROR_FACE_RECOGNITION_SERVER_PICTURE_DPI_ERROR:
		return errors.New("图片分辨率异常")
	case C.NET_ERROR_FACE_RECOGNITION_SERVER_PICTURE_PX_ERROR:
		return errors.New("图片像素异常")
	case C.NET_ERROR_FACE_RECOGNITION_SERVER_PICTURE_SIZE_ERROR:
		return errors.New("图片大小不对")
	case C.NET_ERROR_FACE_RECOGNITION_SERVER_DATA_BASE_ERROR:
		return errors.New("数据库操作失败")
	case C.NET_ERROR_FACE_RECOGNITION_SERVER_FACE_MAX_NUM:
		return errors.New("人员数量超过限制")
	case C.NET_ERROR_FACE_RECOGNITION_SERVER_BIRTH_DAY_FORMAT_ERROR:
		return errors.New("生日日期格式错误")
	case C.NET_ERROR_FACE_RECOGNITION_SERVER_UID_ERROR:
		return errors.New("人员UID不存在或为空")
	case C.NET_ERROR_FACE_RECOGNITION_SERVER_TOKEN_ERROR:
		return errors.New("令牌不存在或为空")
	case C.NET_ERROR_FACE_RECOGNITION_SERVER_BEGIN_NUM_OVER_RUN:
		return errors.New("查询起始数大于总数")
	case C.NET_ERROR_FACE_RECOGNITION_SERVER_ABSTRACT_NUM_ZERO:
		return errors.New("需手动建模人数为0")
	case C.NET_ERROR_FACE_RECOGNITION_SERVER_ABSTRACT_INIT_ERROR:
		return errors.New("建模分析器启动失败")
	case C.NET_ERROR_FACE_RECOGNITION_SERVER_AUTO_ABSTRACT_STATE:
		return errors.New("设备正在自动建模")
	case C.NET_ERROR_FACE_RECOGNITION_SERVER_ABSTRACT_STATE:
		return errors.New("设备正在手动建模")
	case C.NET_ERROR_FACE_RECOGNITION_SERVER_IM_EX_STATE:
		return errors.New("设备正在导入导出 ")
	case C.NET_ERROR_FACE_RECOGNITION_SERVER_PIC_WRITE_FAILED:
		return errors.New("图片写入失败")
	case C.NET_ERROR_FACE_RECOGNITION_SERVER_GROUP_SPACE_EXCEED:
		return errors.New("超出人脸库空间大小限制")
	case C.NET_ERROR_FACE_RECOGNITION_SERVER_GROUP_PIC_COUNT_EXCEED:
		return errors.New("超出人脸库图片数量限制")
	case C.NET_ERROR_FACE_RECOGNITION_SERVER_GROUP_NOT_FOUND:
		return errors.New("人脸库不存在")
	case C.NET_ERROR_FACE_RECOGNITION_SERVER_FIND_RECORDS_ERROR:
		return errors.New("查询原人脸库数据结果无效")
	case C.NET_ERROR_FACE_RECOGNITION_SERVER_DELETE_PERSON_ERROR:
		return errors.New("删除原人脸库数据失败")
	case C.NET_ERROR_FACE_RECOGNITION_SERVER_DELETE_GROUP_ERROR:
		return errors.New("删除人脸库失败")
	case C.NET_ERROR_FACE_RECOGNITION_SERVER_NAME_FORMAT_ERROR:
		return errors.New("命名格式错误")
	case C.NET_ERROR_FACE_RECOGNITION_SERVER_FILEPATH_NOT_SET:
		return errors.New("图片保存路径未设置")
	// case C.NET_ERROR_DEVICE_PARSE_PROTOCOL:
	// 	return errors.New("设备解析协议错误")
	// case C.NET_ERROR_DEVICE_INVALID_REQUEST:
	// 	return errors.New("设备返回无效请求")
	// case C.NET_ERROR_DEVICE_INTERNAL_ERROR:
	// 	return errors.New("设备内部错误")
	case C.NET_ERROR_DEVICE_REQUEST_TIMEOUT:
		return errors.New("设备内部请求超时")
	case C.NET_ERROR_DEVICE_KEEPALIVE_FAIL:
		return errors.New("设备保活失败")
	case C.NET_ERROR_DEVICE_NETWORK_ERROR:
		return errors.New("设备网络错误")
	case C.NET_ERROR_DEVICE_UNKNOWN_ERROR:
		return errors.New("设备内部未知错误")
	case C.NET_ERROR_DEVICE_COM_INTERFACE_NOTFOUND:
		return errors.New("设备组件接口没有找到")
	case C.NET_ERROR_DEVICE_COM_IMPLEMENT_NOTFOUND:
		return errors.New("设备组件实现没有找到")
	case C.NET_ERROR_DEVICE_COM_NOTFOUND:
		return errors.New("设备接入组件没有找到")
	case C.NET_ERROR_DEVICE_COM_INSTANCE_NOTEXIST:
		return errors.New("设备接入组件实例不存在")
	case C.NET_ERROR_DEVICE_CREATE_COM_FAIL:
		return errors.New("设备组件工厂创建组件失败")
	case C.NET_ERROR_DEVICE_GET_COM_FAIL:
		return errors.New("设备组件工厂获取组件实例失败")
	case C.NET_ERROR_DEVICE_BAD_REQUEST:
		return errors.New("设备业务请求不被接受")
	case C.NET_ERROR_DEVICE_REQUEST_IN_PROGRESS:
		return errors.New("设备已经在处理请求，不接受重复请求")
	case C.NET_ERROR_DEVICE_LIMITED_RESOURCE:
		return errors.New("设备资源不足")
	case C.NET_ERROR_DEVICE_BUSINESS_TIMEOUT:
		return errors.New("设备业务超时")
	case C.NET_ERROR_DEVICE_TOO_MANY_REQUESTS:
		return errors.New("设备接收过多请求")
	case C.NET_ERROR_DEVICE_NOT_ALREADY:
		return errors.New("设备未准备就绪，不接受业务请求")
	case C.NET_ERROR_DEVICE_SEARCHRECORD_TIMEOUT:
		return errors.New("设备录像查询超时")
	case C.NET_ERROR_DEVICE_SEARCHTIME_INVALID:
		return errors.New("设备录像查询时间无效")
	case C.NET_ERROR_DEVICE_SSID_INVALID:
		return errors.New("设备校验SSID无效")
	case C.NET_ERROR_DEVICE_CHANNEL_STREAMTYPE_ERROR:
		return errors.New("设备校验通道号或码流类型无效")
	case C.NET_ERROR_DEVICE_STREAM_PACKINGFORMAT_UNSUPPORT:
		return errors.New("设备不支持该码流打包格式")
	case C.NET_ERROR_DEVICE_AUDIO_ENCODINGFORMAT_UNSUPPORT:
		return errors.New("设备不支持该语音编码格式")
	case C.NET_ERROR_SECURITY_ERROR_SUPPORT_GUI:
		return errors.New("校验请求安全码失败,可使用本地GUI方式重置密码")
	case C.NET_ERROR_SECURITY_ERROR_SUPPORT_MULT:
		return errors.New("校验请求安全码失败,可使用大华渠道APP、configtool工具重置密码")
	case C.NET_ERROR_SECURITY_ERROR_SUPPORT_UNIQUE:
		return errors.New("校验请求安全码失败,可登陆Web页面重置密码")
	case C.NET_ERROR_STREAMCONVERTOR_DEFECT:
		return errors.New("转码库缺失")

	case C.NET_ERROR_SECURITY_GENERATE_SAFE_CODE:
		return errors.New("调用大华加密库产生安全码失败")
	case C.NET_ERROR_SECURITY_GET_CONTACT:
		return errors.New("获取联系方式失败")
	case C.NET_ERROR_SECURITY_GET_QRCODE:
		return errors.New("获取重置密码的二维码信息失败")
	case C.NET_ERROR_SECURITY_CANNOT_RESET:
		return errors.New("设备未初始化,无法重置")
	case C.NET_ERROR_SECURITY_NOT_SUPPORT_CONTACT_MODE:
		return errors.New("不支持设置该种联系方式,如只支持设置手机号，却请求设置邮箱")
	case C.NET_ERROR_SECURITY_RESPONSE_TIMEOUT:
		return errors.New("对端响应超时")
	case C.NET_ERROR_SECURITY_AUTHCODE_FORBIDDEN:
		return errors.New("尝试校验AuthCode次数过多，禁止校验")
	case C.NET_ERROR_TRANCODE_LOGIN_REMOTE_DEV:
		return errors.New("(虚拟转码)登陆远程设备失败")
	case C.NET_ERROR_TRANCODE_NOFREE_CHANNEL:
		return errors.New("(虚拟转码)没有可用的通道资源")
	case C.NET_ERROR_VK_INFO_DECRYPT_FAILED:
		return errors.New("VK信息解密失败")
	case C.NET_ERROR_VK_INFO_DESERIALIZE_FAILED:
		return errors.New("VK信息解析失败")
	case C.NET_ERROR_GDPR_ABILITY_NOT_ENABLE:
		return errors.New("SDK GDPR功能未使能")

	/*门禁快速导入及复核错误码 start*/
	case C.NET_ERROR_FAST_CHECK_NO_AUTH:
		return errors.New("门禁快速复核:无权限")
	case C.NET_ERROR_FAST_CHECK_NO_FILE:
		return errors.New("门禁快速复核:文件不存在")
	case C.NET_ERROR_FAST_CHECK_FILE_FAIL:
		return errors.New("门禁快速复核:文件准备失败")
	case C.NET_ERROR_FAST_CHECK_BUSY:
		return errors.New("门禁快速复核:系统忙")
	case C.NET_ERROR_FAST_CHECK_NO_PASSWORD:
		return errors.New("门禁快速复核:未定义密码, 不允许导出")
	case C.NET_ERROR_IMPORT_ACCESS_SEND_FAILD:
		return errors.New("门禁快速导入:发送门禁数据失败")
	case C.NET_ERROR_IMPORT_ACCESS_BUSY:
		return errors.New("门禁快速导入:系统忙, 已经有导入任务")
	case C.NET_ERROR_IMPORT_ACCESS_DATAERROR:
		return errors.New("门禁快速导入:数据包检验失败")
	case C.NET_ERROR_IMPORT_ACCESS_DATAINVALID:
		return errors.New("门禁快速导入:数据包非法")
	case C.NET_ERROR_IMPORT_ACCESS_SYNC_FALID:
		return errors.New("门禁快速导入:同步失败,数据库无法生成")
	case C.NET_ERROR_IMPORT_ACCESS_DBFULL:
		return errors.New("门禁快速导入:数据库已满, 无法导入")
	case C.NET_ERROR_IMPORT_ACCESS_SDFULL:
		return errors.New("门禁快速导入:存储空间已满, 无法导入")
	case C.NET_ERROR_IMPORT_ACCESS_CIPHER_ERROR:
		return errors.New("门禁快速导入:导入压缩包密码不对")
	/*门禁快速导入及复核错误码 end*/

	case C.NET_ERROR_INVALID_PARAM:
		return errors.New("参数无效")
	case C.NET_ERROR_INVALID_PASSWORD:
		return errors.New("密码无效")
	case C.NET_ERROR_INVALID_FINGERPRINT:
		return errors.New("指纹无效")
	case C.NET_ERROR_INVALID_FACE:
		return errors.New("人脸无效")
	case C.NET_ERROR_INVALID_CARD:
		return errors.New("卡无效")
	case C.NET_ERROR_INVALID_USER:
		return errors.New("用户无效")
	case C.NET_ERROR_GET_SUBSERVICE:
		return errors.New("能力集子服务获取失败")
	case C.NET_ERROR_GET_METHOD:
		return errors.New("获取组件的方法集失败")
	case C.NET_ERROR_GET_SUBCAPS:
		return errors.New("获取资源实体能力集失败")
	case C.NET_ERROR_UPTO_INSERT_LIMIT:
		return errors.New("已达插入上限")
	case C.NET_ERROR_UPTO_MAX_INSERT_RATE:
		return errors.New("已达最大插入速度")
	case C.NET_ERROR_ERASE_FINGERPRINT:
		return errors.New("清除指纹数据失败")
	case C.NET_ERROR_ERASE_FACE:
		return errors.New("清除人脸数据失败")
	case C.NET_ERROR_ERASE_CARD:
		return errors.New("清除卡数据失败")
	case C.NET_ERROR_NO_RECORD:
		return errors.New("没有记录")
	case C.NET_ERROR_NOMORE_RECORDS:
		return errors.New("查找到最后，没有更多记录")
	case C.NET_ERROR_RECORD_ALREADY_EXISTS:
		return errors.New("下发卡或指纹时，数据重复")
	case C.NET_ERROR_EXCEED_MAX_FINGERPRINT_PERUSER:
		return errors.New("超过个人最大指纹记录数")
	case C.NET_ERROR_EXCEED_MAX_CARD_PERUSER:
		return errors.New("超过个人最大卡片记录数	")
	case C.NET_ERROR_EXCEED_ADMINISTRATOR_LIMIT:
		return errors.New("超过门禁管理员个数限制")

	case C.NET_LOGIN_ERROR_DEVICE_NOT_SUPPORT_HIGHLEVEL_SECURITY_LOGIN:
		return errors.New("设备不支持高安全等级登录")
	case C.NET_LOGIN_ERROR_DEVICE_ONLY_SUPPORT_HIGHLEVEL_SECURITY_LOGIN:
		return errors.New("设备只支持高安全等级登录")

	case C.NET_ERROR_VIDEO_CHANNEL_OFFLINE:
		return errors.New("表示此视频通道处于离线，拉流失败")
	case C.NET_ERROR_USERID_FORMAT_INCORRECT:
		return errors.New("用户编号不规范")
	case C.NET_ERROR_CANNOT_FIND_CHANNEL_RELATE_TO_SN:
		return errors.New("找不到该SN对应的通道")
	case C.NET_ERROR_TASK_QUEUE_OF_CHANNEL_IS_FULL:
		return errors.New("该通道的任务队列满")
	case C.NET_ERROR_APPLY_USER_INFO_BLOCK_FAIL:
		return errors.New("申请不到新的用户信息(权限)块")
	case C.NET_ERROR_EXCEED_MAX_PASSWD_PERUSER:
		return errors.New("用户密码数量超过限制")
	case C.NET_ERROR_PARSE_PROTOCOL:
		return errors.New("设备内部异常引起协议解析错误")
	case C.NET_ERROR_CARD_NUM_EXIST:
		return errors.New("卡号已存在")
	case C.NET_ERROR_FINGERPRINT_EXIST:
		return errors.New("指纹已存在")

	case C.NET_ERROR_OPEN_PLAYGROUP_FAIL:
		return errors.New("打开播放组失败")
	case C.NET_ERROR_ALREADY_IN_PLAYGROUP:
		return errors.New("已位于播放组中")
	case C.NET_ERROR_QUERY_PLAYGROUP_TIME_FAIL:
		return errors.New("查询播放组时间失败")
	case C.NET_ERROR_SET_PLAYGROUP_BASECHANNEL_FAIL:
		return errors.New("设置播放组基准通道失败")
	case C.NET_ERROR_SET_PLAYGROUP_DIRECTION_FAIL:
		return errors.New("设置播放组方向失败")
	case C.NET_ERROR_SET_PLAYGROUP_SPEED_FAIL:
		return errors.New("设置播放组速度失败")
	case C.NET_ERROR_ADD_PLAYGROUP_FAIL:
		return errors.New("加入播放组失败")
	case C.NET_ERROR_EXPORT_AOL_LOGFILE_NO_AUTH:
		return errors.New("导出AOL日志:无权限")
	case C.NET_ERROR_EXPORT_AOL_LOGFILE_NO_FILE:
		return errors.New("导出AOL日志:文件不存在")
	case C.NET_ERROR_EXPORT_AOL_LOGFILE_FILE_FAIL:
		return errors.New("导出AOL日志:文件准备失败")
	case C.NET_ERROR_EXPORT_AOL_LOGFILE_BUSY:
		return errors.New("导出AOL日志:系统忙")
	// 设备上APP安装相关错误码
	case C.NET_ERROR_EMPTY_LICENSE:
		return errors.New("License为空")
	case C.NET_ERROR_UNSUPPORTED_MODE:
		return errors.New("不支持该模式")
	case C.NET_ERROR_URL_APP_NOT_MATCH:
		return errors.New("URL与APP不匹配")
	case C.NET_ERROR_READ_INFO_FAILED:
		return errors.New("读取信息失败")
	case C.NET_ERROR_WRITE_FAILED:
		return errors.New("写入失败")
	case C.NET_ERROR_NO_SUCH_APP:
		return errors.New("未找到APP")
	case C.NET_ERROR_VERIFIF_FAILED:
		return errors.New("校验失败")
	case C.NET_ERROR_LICENSE_OUT_DATE:
		return errors.New("License已过期")
	case C.NET_ERROR_UPGRADE_PROGRAM_TOO_OLD:
		return errors.New("升级程序版本过低")
	default:
		return errors.New("未知错误")
	}
}
